"""new cover field in book model

Revision ID: 57d2e0ae97ea
Revises: 772a16c1ed6b
Create Date: 2022-01-21 17:34:33.654509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d2e0ae97ea'
down_revision = '772a16c1ed6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('cover', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'cover')
    # ### end Alembic commands ###
