"""isbn fields

Revision ID: 8bad1256e64d
Revises: d09b52a1068f
Create Date: 2022-01-24 00:54:21.254205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bad1256e64d'
down_revision = 'd09b52a1068f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('isbn_10',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('isbn_13',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
        batch_op.drop_index('ix_book_isbn_10')
        batch_op.create_index(batch_op.f('ix_book_isbn_10'), ['isbn_10'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_isbn_10'))
        batch_op.create_index('ix_book_isbn_10', ['isbn_10'], unique=False)
        batch_op.alter_column('isbn_13',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
        batch_op.alter_column('isbn_10',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
