"""temporarily drop loan table

Revision ID: accc2b8fa4b7
Revises: 25ae46cf5a6f
Create Date: 2022-01-27 02:45:11.828313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'accc2b8fa4b7'
down_revision = '25ae46cf5a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_index('ix_loan_in_timestamp')
        batch_op.drop_index('ix_loan_out_timestamp')
        batch_op.drop_index('ix_loan_phone_num')
        batch_op.drop_index('ix_loan_returned')

    op.drop_table('loan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('out_timestamp', sa.DATE(), nullable=True),
    sa.Column('in_timestamp', sa.DATE(), nullable=False),
    sa.Column('returned', sa.BOOLEAN(), nullable=False),
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.Column('phone_num', sa.VARCHAR(length=10), nullable=False),
    sa.Column('loanee', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id')
    )
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.create_index('ix_loan_returned', ['returned'], unique=False)
        batch_op.create_index('ix_loan_phone_num', ['phone_num'], unique=False)
        batch_op.create_index('ix_loan_out_timestamp', ['out_timestamp'], unique=False)
        batch_op.create_index('ix_loan_in_timestamp', ['in_timestamp'], unique=False)

    # ### end Alembic commands ###
