"""Changed isbn fields

Revision ID: e1caa051e138
Revises: 57d2e0ae97ea
Create Date: 2022-01-24 00:44:49.354973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1caa051e138'
down_revision = '57d2e0ae97ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'isbn_10',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('book', 'isbn_13',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
    op.drop_index('ix_book_isbn_10', table_name='book')
    op.create_index(op.f('ix_book_isbn_10'), 'book', ['isbn_10'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_isbn_10'), table_name='book')
    op.create_index('ix_book_isbn_10', 'book', ['isbn_10'], unique=False)
    op.alter_column('book', 'isbn_13',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
    op.alter_column('book', 'isbn_10',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
